Master:
  InstallPlugins:
    - kubernetes:1.14.9
    - workflow-job:2.32
    - workflow-aggregator:2.6
    - credentials-binding:1.18
    - git:3.9.3
    - google-oauth-plugin:0.7
    - google-source-plugin:0.3
    - github:1.29.4
    - github-branch-source:2.4.2
    - basic-branch-build-strategies:1.2.0
  Cpu: "100m"
  Memory: "1024Mi"
  JavaOpts: "-Xms1024m -Xmx1024m"
  ServiceType: NodePort
  AdminPassword: password
Agent:
  Enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "300m"
      memory: "512Mi"
Persistence:
  Size: 20Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins
