apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "lb-k8s"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cd-jenkins
          servicePort: 8080
